name: Health check

on:
  schedule:
    - cron: 15 * * * * 
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-22.04
    steps:
      - name: Check service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: http://powerful-fortress-45246.herokuapp.com/health
          follow-redirect: false
          retry-delay: 5s
          retry-all: false